# config.yaml
data:
  num_seeds: 10
  name: "bimodal"
  N_x: 5000
  N_y: 50

model:
  feature: 50
  sig_init: 0.1
  lamb: 0.1
  median: false

optimizer:
  lr: 1e-4
  weight_decay: true

train:
  epoch: 1000
  batch_size: 50

test:
  num_sample: 50
  num_bin: 1000

mlflow: 
  runname: "sample"
