# config.yaml
data:
  num_seeds: 20
  name: "uci"
  data_path: "bostonHousing/data"

model:
  numAtom: 100
  sig_init: 1.0
  type: "small"

optimizer:
  lr: 5e-4
  hyper_lr: 5e-4
  weight_decay: true

train:
  epoch: 500
  batch_size: 32
  update_period: 1

test:
  num_sample: 1000
  num_bin: 1000

mlflow: 
  runname: "sample"
